### ISSUE TITLE
Wongift admin paneli giveaways kısmı edit problemi

### ISSUE THREAD

**Issue by dogukancece** [kvlknctk/cekilis#20]
Admin panelinde giveawayi editlemek istediğimde onaylayabilmem için tekrar resim seçmem gerekiyor. Bu sorunun düzeltilmesi lazım. Direk resim seçmedende editleyebilmeliyim.

**Comment by dogukancece** [comment]
<script data-ad-client="ca-pub-1214068731511546" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

**Comment by kvlknctk** [comment]
`<script data-ad-client="ca-pub-1214068731511546" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js">
</script>`
