### ISSUE TITLE
My items için key id girilmesi gerekiyor.

### ISSUE THREAD

**Issue by kvlknctk** [kvlknctk/cekilis#9]
loglara dikkat ettiğimizde hata veriyor zaten resul. döngüde olan her dom key={item.id} propuna sahip olması gerekiyor. pek önemli değil ama bilinmesi gereken bir konu diye düşünüyorum.

**Comment by resulozel** [comment]
notlara alındı.

**Comment by resulozel** [comment]
import React, { Component } from 'react'
import { render } from 'react-dom'

const data = [
  {id: 'a', name: 'Devin'},
  {id: 'b', name: 'Gabe' },
  {id: 'c', name: 'Kim'},
]

class List extends Component {
  render() {
    return (
      <div>
        {data.map(item => <div key={item.id}>{item.name}</div>)}
      </div>
    )
  }
}

render(<List />, document.querySelector('#app'))

**Comment by resulozel** [comment]
böyle bir örnek baktımda, acaba bunun için önayak olur mu abi ?
